name: Python Unit Test

on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      JWT_SECRET: ${{ secrets.JWT_SECRET }}
      DbUser: ${{ secrets.DbUser }}
      DbGeo: ${{ secrets.DbGeo }}  
      DbPath: ${{ secrets.DbPath }}
    steps:

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9.12

    - name: Install dependencies
      run: |
        echo "Installing requirements..."
        pip install -r requirements.txt
    - name: Run unit tests
      run: |
        echo "Testing..."
        python -m pytest --import-mode=append src/fastapi/
          