AWS_ACCESS_KEY_ID = "AKIA3EJL4FYTQOGZWUOB"
AWS_SECRET_ACCESS_KEY = "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"
LOG_GROUP_NAME = "damg7245_Assignment1"
LOG_STREAM_NAME_AWS = "aws_services"
LOG_STREAMLIT_NAME = "streamlit_ui"
LOG_DATABASE_NAME = "database"
BUCKET_NAME = "damg7245-s3-storage"
JWT_SECRET="damg_7225_big_data" 